title: Computer Architecture Conference Deadlines # (Maintained by @mktrm)
# email: mktrm@ucsd.edu
description: Countdowns to computer architecture conference deadlines
author: Kazem Taram

domain: "mktrm.github.io"
baseurl: "arch-deadlines"
baseurl: ""

twitter_username: mktaram
twitter_hashtag: architecture
github_username: mktrm
github_repo: arch-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
theme: jekyll-theme-cayman
