title: ES Conference Deadlines
description: Countdowns to top ES conference deadlines
author: Abhishek Das

domain: "ekut-es.github.io"
baseurl: "/es-deadlines"

twitter_username: 
twitter_hashtag: embeddedsystems
github_username: ekut-es
github_repo: es-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
